version: '3.8'

services:
  advanced-parser:
    build:
      context: .
      dockerfile: Dockerfile
    image: aarch64-rag_pypeline:latest
    container_name: rag_pypeline
    ports:
      - "38808:8000"
    networks:
      - ai-net   # Change this to the exact name of your existing docker network
    restart: always

networks:
  ai-net:
    external: true
